### PR TITLE
Add fixed chat prompt

### LINKED ISSUE #21: create a fixed floating Chat prompt

### PR DESCRIPTION
**Pull request by juzQrios**
closes #21

### CODE REVIEW

**Comment by juzQrios** [comment]
Suggestions on class name?

**Comment by SumanKisku** [comment]
@juzQrios like "message-fixed".

**Comment by juzQrios** [comment]
Will change it to "message-fixed" right away

**Comment by SumanKisku** [comment]
"fixed-chat-prompt" is also good. I think.

**Pull request merged**
